services:
  - type: web
    name: armonia-web
    runtime: python
    plan: free
    region: frankfurt # Más cercano a España
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn --workers 1 --timeout 120 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: FLASK_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: 1
    healthCheckPath: /
